# Generated by Django 3.2 on 2025-05-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='descriptinon',
            new_name='description',
        ),
    ]
